### ISSUE TITLE
6 terms less

### ISSUE THREAD

**Issue by BenWiederhake** [SandSnip3r/RandomPostfixEquation#1]
Just by looking at the expression, one can easily reduce it to:

```
69 69 / 69 69 + 69 420 69 69 69 / 69 + + 69 420 + - / * * 69 / 69 420 420 + / / -  (16 terms)
69 69 / 69 69 + 420 420 420 + * 420 69 - 69 69 / - 69 * / * + (12 terms)
```

"Efficient" exhaustive enumeration is rather easy to do (just keep an open/closed list, runs in time O(n²) with n discovered partial expressions). However, it's not so trivial to enumerate them in such a way that the shortest possible representation will be found.  Would you be interested in a PR that does that?

**Comment by SandSnip3r** [comment]
It doesn't seem obvious to me how you were able to reduce the equation.

Also, yes, I am curious to see an implementation of what you mention.

**Comment by BenWiederhake** [comment]
Drop this into your favorite LaTeX compiler:
```
\begin{align*}
    &{} \frac{69}{69} - (69 + 69) \times 69 \times \frac{\frac{\frac{420}{69 + \frac{69}{69} + 69 - (69 + 420)}}{69}}{\frac{69}{420 + 420}} \\
    &= \frac{69}{69} - (69 + 69) \times 69 \times \frac{\frac{\frac{420}{69 + \frac{69}{69} - 420}}{69}}{\frac{69}{420 + 420}} \\
    &= \frac{69}{69} - (69 + 69) \times 69 \times \frac{  \frac{420}{69 + \frac{69}{69} - 420} \times (420 + 420)  }{69 \times 69} \\
    &= \frac{69}{69} - (69 + 69) \times \frac{  \frac{420}{69 + \frac{69}{69} - 420} \times (420 + 420)  }{69} \\
    &= \frac{69}{69} - (69 + 69) \times \frac{  420 \times (420 + 420)  }{(69 + \frac{69}{69} - 420) \times 69} \\
    &= \frac{69}{69} + (69 + 69) \times \frac{  420 \times (420 + 420)  }{(420 - 69 - \frac{69}{69}) \times 69} \\
    %  (  69 69 /  )   (69 69 +)                (   420 420 420 + *  )   ( 420 69 - 69 69 / -        69 *     )
    %  (  69 69 /  )   (69 69 +)        (           420 420 420 + *        420 69 - 69 69 / -        69 * /   )
    %  (  69 69 /  )   (69 69 +                     420 420 420 + *        420 69 - 69 69 / -        69 * / * )
    %  (  69 69 /       69 69 +                     420 420 420 + *        420 69 - 69 69 / -        69 * / *+)
    % 69 69 / 69 69 + 420 420 420 + * 420 69 - 69 69 / - 69 * / * +
    &= 1 + 2 \times \frac{420 \times (420 + 420)}{420 - 69 - \frac{69}{69}} \\
    &= 1 + 2 \times \frac{420 \times 420 \times 2}{420 - 69 - 1} \\
    &= 1 + 2 \times \frac{420 \times 420 \times 2}{350} \\
    &= 1 + \frac{420 \times 60 \times 2}{25} \\
    &= 1 + 84 \times 12 \times 2 \\
    &= 1 + 2016 \\
    &= 2017 \\
\end{align*}
```

@implementation: I'll give it a shot.

**Comment by BenWiederhake** [comment]
So I wrote a brute-force-ish search from scratch: https://github.com/BenWiederhake/minprn

I couldn't re-use any of your code, because the approach is quite different, and the main data structure (the open list) has literally nothing in common with this project.  So I won't open a PR, I hope you don't mind :)

Also, here's an expression with only 10 terms that evaluates to 2017: https://www.wolframalpha.com/input/?i=%5Cfrac%7B69%7D%7B69%7D+-+%5Cfrac%7B%28420%2B420%29*%28420%2B420%29%7D%7B69-420%2B%5Cfrac%7B69%7D%7B69%7D%7D

As the `README` of my project explains, it's not really guaranteed that this is the shortest possible expression, but at least it's the shortest possible expression of which all intermediate results are whole integers within some sane range.

Closing this because, well, there's no issue anymore.
